spring:
  #数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fiction?&serverTimezone=UTC
#    url: jdbc:mysql://1.13.0.249:3306/fiction?&serverTimezone=UTC
#    url: jdbc:mysql://mysql:3306/fiction?&serverTimezone=UTC
    username: root
    password: admin
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j2
      use-global-data-source-stat: true
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false
        url-pattern: /druid/*
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  redis:
#    host: redis
    host: 127.0.0.1
#    host: 1.13.0.249
    port: 6379
    database: 0
    timeout: 1000
    lettuce:
      pool:
        max-active: 12
        max-wait: -1
        max-idle: 8
        min-idle: 1


  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**

mybatis:
  typeAliasesPackage: com.cither.pojo
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


